/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { AxelarGateway__factory } from "./AxelarGateway__factory";
export { TestToken__factory } from "./TestToken__factory";
